name: JSdoc

on:
  # Triggers the workflow on push events but only for the main or dev branch
  push:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: push

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Set up workspace
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build documention
        run: npx -y typedoc src/index.js src/detect.js src/terminal.js

      - name: Auto commit
        run: |
          git add .
          git -c user.name='jsdoc-bot' -c user.email='speed-highlight@protonmail.com' commit -m "Doc update" || exit 0
          git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
