name: Minify

on:
  # Triggers the workflow on push events but only for the main or dev branch
  push:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: push

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Set up workspace
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm i

      - name: Build the packages
        run: npm run build

      - name: Auto commit
        run: |
          git add .
          git -c user.name='minify-bot' -c user.email='speed-highlight@protonmail.com' commit -m "Auto minify" || exit 0
          git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
