name: Release

"on":
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

concurrency:
  group: push

jobs:
  release:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: actions/checkout@v3 # v3

      - name: Setup Node
        uses: actions/setup-node@v3 # v3
        with:
          cache: npm
          node-version: lts/*

      - run: npm clean-install
      - run: npm audit signatures
      - run: npm run build

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}